"""
python validate_segments.py --model large-v3 --batch-size 4 --manifest tts_segments/train1.jsonl --base-dir tts_segments --language ms
"""


import argparse
import json
import re
from difflib import SequenceMatcher
from pathlib import Path

import torch
import whisperx


TRADITIONAL_TO_SIMPLIFIED = str.maketrans(
    {
        "與": "与",
        "專": "专",
        "業": "业",
        "東": "东",
        "絲": "丝",
        "兩": "两",
        "嚴": "严",
        "喪": "丧",
        "個": "个",
        "豐": "丰",
        "臨": "临",
        "為": "为",
        "麗": "丽",
        "舉": "举",
        "義": "义",
        "烏": "乌",
        "樂": "乐",
        "習": "习",
        "鄉": "乡",
        "書": "书",
        "買": "买",
        "亂": "乱",
        "爭": "争",
        "於": "于",
        "虧": "亏",
        "雲": "云",
        "亞": "亚",
        "產": "产",
        "畝": "亩",
        "親": "亲",
        "億": "亿",
        "僅": "仅",
        "從": "从",
        "倉": "仓",
        "儀": "仪",
        "們": "们",
        "優": "优",
        "會": "会",
        "傘": "伞",
        "偉": "伟",
        "傳": "传",
        "傷": "伤",
        "價": "价",
        "儉": "俭",
        "倆": "俩",
        "係": "系",
        "俠": "侠",
        "侶": "侣",
        "側": "侧",
        "偵": "侦",
        "僑": "侨",
        "儂": "侬",
        "俁": "俣",
        "儔": "俦",
        "儼": "俨",
        "倀": "伥",
        "倆": "俩",
        "備": "备",
        "債": "债",
        "傾": "倾",
        "僂": "偻",
        "僥": "侥",
        "償": "偿",
        "兒": "儿",
        "內": "内",
        "兩": "两",
        "冊": "册",
        "冪": "幂",
        "凍": "冻",
        "凈": "净",
        "準": "准",
        "減": "减",
        "凱": "凯",
        "別": "别",
        "刪": "删",
        "剛": "刚",
        "創": "创",
        "劃": "划",
        "劇": "剧",
        "劉": "刘",
        "劍": "剑",
        "劑": "剂",
        "勁": "劲",
        "動": "动",
        "務": "务",
        "勞": "劳",
        "勢": "势",
        "勵": "励",
        "勸": "劝",
        "區": "区",
        "協": "协",
        "單": "单",
        "賣": "卖",
        "卻": "却",
        "廠": "厂",
        "歷": "历",
        "厲": "厉",
        "壓": "压",
        "縣": "县",
        "參": "参",
        "雙": "双",
        "發": "发",
        "變": "变",
        "敘": "叙",
        "臺": "台",
        "號": "号",
        "後": "后",
        "嚮": "向",
        "嗎": "吗",
        "啟": "启",
        "吳": "吴",
        "員": "员",
        "問": "问",
        "啞": "哑",
        "聽": "听",
        "啟": "启",
        "喚": "唤",
        "喪": "丧",
        "喬": "乔",
        "單": "单",
        "嚴": "严",
        "囑": "嘱",
        "噴": "喷",
        "噸": "吨",
        "園": "园",
        "圍": "围",
        "國": "国",
        "圖": "图",
        "圓": "圆",
        "聖": "圣",
        "場": "场",
        "壞": "坏",
        "塊": "块",
        "堅": "坚",
        "壇": "坛",
        "墜": "坠",
        "壩": "坝",
        "壓": "压",
        "壘": "垒",
        "壙": "圹",
        "壯": "壮",
        "聲": "声",
        "處": "处",
        "備": "备",
        "複": "复",
        "夠": "够",
        "頭": "头",
        "夾": "夹",
        "奪": "夺",
        "奮": "奋",
        "婦": "妇",
        "媽": "妈",
        "娛": "娱",
        "嬰": "婴",
        "學": "学",
        "寧": "宁",
        "寶": "宝",
        "實": "实",
        "審": "审",
        "寫": "写",
        "寬": "宽",
        "對": "对",
        "導": "导",
        "將": "将",
        "專": "专",
        "尋": "寻",
        "層": "层",
        "屬": "属",
        "歲": "岁",
        "峽": "峡",
        "島": "岛",
        "嶺": "岭",
        "嶼": "屿",
        "巖": "岩",
        "幣": "币",
        "師": "师",
        "帶": "带",
        "幫": "帮",
        "幹": "干",
        "庫": "库",
        "廁": "厕",
        "廂": "厢",
        "廈": "厦",
        "廚": "厨",
        "廢": "废",
        "廣": "广",
        "廳": "厅",
        "彈": "弹",
        "強": "强",
        "歸": "归",
        "當": "当",
        "錄": "录",
        "彎": "弯",
        "張": "张",
        "徑": "径",
        "從": "从",
        "徠": "徕",
        "復": "复",
        "徵": "征",
        "憶": "忆",
        "懷": "怀",
        "態": "态",
        "總": "总",
        "恆": "恒",
        "恥": "耻",
        "悅": "悦",
        "惡": "恶",
        "惱": "恼",
        "懸": "悬",
        "驚": "惊",
        "愛": "爱",
        "慣": "惯",
        "慘": "惨",
        "慚": "惭",
        "慶": "庆",
        "憂": "忧",
        "憐": "怜",
        "憑": "凭",
        "應": "应",
        "懲": "惩",
        "懶": "懒",
        "懷": "怀",
        "懼": "惧",
        "戀": "恋",
        "戰": "战",
        "戶": "户",
        "扎": "扎",
        "撲": "扑",
        "執": "执",
        "擴": "扩",
        "掃": "扫",
        "揚": "扬",
        "擾": "扰",
        "撫": "抚",
        "拋": "抛",
        "挾": "挟",
        "捨": "舍",
        "捲": "卷",
        "掃": "扫",
        "掄": "抡",
        "掙": "挣",
        "掛": "挂",
        "採": "采",
        "揀": "拣",
        "換": "换",
        "揮": "挥",
        "損": "损",
        "搖": "摇",
        "搶": "抢",
        "摑": "掴",
        "摜": "掼",
        "摯": "挚",
        "摳": "抠",
        "摶": "抟",
        "撈": "捞",
        "撐": "撑",
        "撥": "拨",
        "撫": "抚",
        "撲": "扑",
        "撳": "揿",
        "撻": "挞",
        "撾": "挝",
        "擁": "拥",
        "擇": "择",
        "擊": "击",
        "擋": "挡",
        "擔": "担",
        "據": "据",
        "擠": "挤",
        "擬": "拟",
        "擱": "搁",
        "擴": "扩",
        "擲": "掷",
        "擺": "摆",
        "擾": "扰",
        "攜": "携",
        "攝": "摄",
        "攤": "摊",
        "攪": "搅",
        "敗": "败",
        "敘": "叙",
        "數": "数",
        "斂": "敛",
        "斃": "毙",
        "斷": "断",
        "無": "无",
        "舊": "旧",
        "時": "时",
        "曠": "旷",
        "暢": "畅",
        "暫": "暂",
        "曆": "历",
        "書": "书",
        "會": "会",
        "術": "术",
        "機": "机",
        "殺": "杀",
        "雜": "杂",
        "權": "权",
        "條": "条",
        "來": "来",
        "楊": "杨",
        "極": "极",
        "構": "构",
        "標": "标",
        "樓": "楼",
        "樣": "样",
        "樁": "桩",
        "樂": "乐",
        "樞": "枢",
        "樹": "树",
        "橋": "桥",
        "機": "机",
        "橫": "横",
        "檔": "档",
        "檢": "检",
        "櫃": "柜",
        "權": "权",
        "歡": "欢",
        "歐": "欧",
        "歲": "岁",
        "歷": "历",
        "歸": "归",
        "殘": "残",
        "毀": "毁",
        "氣": "气",
        "氫": "氢",
        "氬": "氩",
        "氳": "氲",
        "決": "决",
        "況": "况",
        "沒": "没",
        "沖": "冲",
        "溝": "沟",
        "沒": "没",
        "淚": "泪",
        "淨": "净",
        "淺": "浅",
        "渦": "涡",
        "測": "测",
        "渾": "浑",
        "湊": "凑",
        "減": "减",
        "湧": "涌",
        "準": "准",
        "溫": "温",
        "滅": "灭",
        "滾": "滚",
        "滿": "满",
        "濾": "滤",
        "濫": "滥",
        "災": "灾",
        "灣": "湾",
        "為": "为",
        "烏": "乌",
        "無": "无",
        "煉": "炼",
        "煙": "烟",
        "熱": "热",
        "燈": "灯",
        "燒": "烧",
        "營": "营",
        "爐": "炉",
        "爭": "争",
        "爲": "为",
        "爺": "爷",
        "牆": "墙",
        "獎": "奖",
        "獨": "独",
        "獲": "获",
        "環": "环",
        "現": "现",
        "瑪": "玛",
        "產": "产",
        "畝": "亩",
        "畫": "画",
        "異": "异",
        "當": "当",
        "疇": "畴",
        "療": "疗",
        "發": "发",
        "盜": "盗",
        "監": "监",
        "盤": "盘",
        "盧": "卢",
        "眾": "众",
        "著": "着",
        "矚": "瞩",
        "礦": "矿",
        "碼": "码",
        "確": "确",
        "礙": "碍",
        "禮": "礼",
        "禍": "祸",
        "禦": "御",
        "離": "离",
        "種": "种",
        "稱": "称",
        "穩": "稳",
        "積": "积",
        "窮": "穷",
        "竄": "窜",
        "竅": "窍",
        "競": "竞",
        "筆": "笔",
        "筍": "笋",
        "築": "筑",
        "範": "范",
        "簡": "简",
        "簽": "签",
        "籌": "筹",
        "籠": "笼",
        "粵": "粤",
        "糧": "粮",
        "糾": "纠",
        "紀": "纪",
        "約": "约",
        "紅": "红",
        "級": "级",
        "紛": "纷",
        "紙": "纸",
        "紡": "纺",
        "紐": "纽",
        "線": "线",
        "練": "练",
        "組": "组",
        "細": "细",
        "終": "终",
        "絆": "绊",
        "結": "结",
        "絕": "绝",
        "絞": "绞",
        "統": "统",
        "絲": "丝",
        "絡": "络",
        "給": "给",
        "絢": "绚",
        "經": "经",
        "綁": "绑",
        "綏": "绥",
        "綜": "综",
        "綠": "绿",
        "綢": "绸",
        "維": "维",
        "綱": "纲",
        "網": "网",
        "緊": "紧",
        "緒": "绪",
        "緩": "缓",
        "編": "编",
        "緣": "缘",
        "縛": "缚",
        "縣": "县",
        "縱": "纵",
        "總": "总",
        "績": "绩",
        "繁": "繁",
        "織": "织",
        "繞": "绕",
        "繩": "绳",
        "繪": "绘",
        "繳": "缴",
        "繼": "继",
        "續": "续",
        "纏": "缠",
        "纖": "纤",
        "纜": "缆",
        "罰": "罚",
        "罷": "罢",
        "羅": "罗",
        "羈": "羁",
        "義": "义",
        "習": "习",
        "聖": "圣",
        "聞": "闻",
        "聯": "联",
        "聰": "聪",
        "聲": "声",
        "聳": "耸",
        "職": "职",
        "聽": "听",
        "腦": "脑",
        "腳": "脚",
        "脫": "脱",
        "臉": "脸",
        "臟": "脏",
        "臺": "台",
        "與": "与",
        "興": "兴",
        "舉": "举",
        "艦": "舰",
        "艙": "舱",
        "藝": "艺",
        "節": "节",
        "莊": "庄",
        "華": "华",
        "萬": "万",
        "萊": "莱",
        "葉": "叶",
        "著": "着",
        "葦": "苇",
        "蒼": "苍",
        "蓋": "盖",
        "藍": "蓝",
        "藝": "艺",
        "蘇": "苏",
        "處": "处",
        "虛": "虚",
        "蟲": "虫",
        "號": "号",
        "衛": "卫",
        "衝": "冲",
        "補": "补",
        "裝": "装",
        "複": "复",
        "褲": "裤",
        "襲": "袭",
        "見": "见",
        "規": "规",
        "視": "视",
        "覺": "觉",
        "覽": "览",
        "觀": "观",
        "觸": "触",
        "訂": "订",
        "計": "计",
        "訊": "讯",
        "訓": "训",
        "記": "记",
        "講": "讲",
        "謝": "谢",
        "謠": "谣",
        "謙": "谦",
        "謹": "谨",
        "證": "证",
        "譜": "谱",
        "識": "识",
        "譯": "译",
        "議": "议",
        "護": "护",
        "譽": "誉",
        "讀": "读",
        "變": "变",
        "讓": "让",
        "讚": "赞",
        "財": "财",
        "責": "责",
        "賢": "贤",
        "敗": "败",
        "賬": "账",
        "貨": "货",
        "質": "质",
        "販": "贩",
        "貪": "贪",
        "貧": "贫",
        "購": "购",
        "貫": "贯",
        "貴": "贵",
        "貸": "贷",
        "費": "费",
        "貼": "贴",
        "貿": "贸",
        "賀": "贺",
        "賃": "赁",
        "賄": "贿",
        "資": "资",
        "賈": "贾",
        "賊": "贼",
        "賓": "宾",
        "賜": "赐",
        "賞": "赏",
        "賠": "赔",
        "賢": "贤",
        "賣": "卖",
        "賤": "贱",
        "賦": "赋",
        "質": "质",
        "賬": "账",
        "賭": "赌",
        "賴": "赖",
        "贈": "赠",
        "贊": "赞",
        "趨": "趋",
        "跡": "迹",
        "踐": "践",
        "躍": "跃",
        "車": "车",
        "軌": "轨",
        "軒": "轩",
        "轉": "转",
        "輪": "轮",
        "輯": "辑",
        "輸": "输",
        "轄": "辖",
        "辦": "办",
        "辭": "辞",
        "邊": "边",
        "遼": "辽",
        "達": "达",
        "遷": "迁",
        "過": "过",
        "運": "运",
        "還": "还",
        "這": "这",
        "進": "进",
        "遠": "远",
        "違": "违",
        "連": "连",
        "遲": "迟",
        "適": "适",
        "選": "选",
        "遺": "遗",
        "郵": "邮",
        "鄉": "乡",
        "鄭": "郑",
        "醫": "医",
        "醬": "酱",
        "釋": "释",
        "釐": "厘",
        "針": "针",
        "鈉": "钠",
        "鋼": "钢",
        "錄": "录",
        "錢": "钱",
        "錯": "错",
        "鍊": "炼",
        "鎮": "镇",
        "鏡": "镜",
        "鐵": "铁",
        "鑑": "鉴",
        "鑒": "鉴",
        "長": "长",
        "門": "门",
        "閃": "闪",
        "閉": "闭",
        "開": "开",
        "閒": "闲",
        "間": "间",
        "閘": "闸",
        "閣": "阁",
        "閱": "阅",
        "闆": "板",
        "闊": "阔",
        "隊": "队",
        "陽": "阳",
        "陰": "阴",
        "陣": "阵",
        "階": "阶",
        "際": "际",
        "陸": "陆",
        "險": "险",
        "隨": "随",
        "隱": "隐",
        "隸": "隶",
        "難": "难",
        "電": "电",
        "霧": "雾",
        "靈": "灵",
        "靜": "静",
        "響": "响",
        "頁": "页",
        "頂": "顶",
        "項": "项",
        "順": "顺",
        "須": "须",
        "預": "预",
        "領": "领",
        "頒": "颁",
        "頻": "频",
        "題": "题",
        "額": "额",
        "顏": "颜",
        "願": "愿",
        "類": "类",
        "風": "风",
        "飛": "飞",
        "飯": "饭",
        "餘": "余",
        "館": "馆",
        "饋": "馈",
        "馬": "马",
        "駐": "驻",
        "駕": "驾",
        "驗": "验",
        "驅": "驱",
        "鬥": "斗",
        "魚": "鱼",
        "鮮": "鲜",
        "鳥": "鸟",
        "鹽": "盐",
        "麗": "丽",
        "麥": "麦",
        "黃": "黄",
        "點": "点",
        "齊": "齐",
        "齒": "齿",
        "龍": "龙",
    }
)


def normalize_text(text):
    text = text.lower()
    text = text.translate(TRADITIONAL_TO_SIMPLIFIED)
    return re.sub(r"[\s，。！？、；：,.!?;:\"'“”‘’《》（）()\[\]【】\-—·%]+", "", text)


def similarity(expected, actual):
    expected = normalize_text(expected)
    actual = normalize_text(actual)

    if not expected and not actual:
        return 1.0

    if not expected or not actual:
        return 0.0

    return SequenceMatcher(None, expected, actual, autojunk=False).ratio()


def load_manifest(path):
    rows = []
    with path.open("r", encoding="utf-8-sig") as f:
        for line_number, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue

            row = json.loads(line)
            row["_line_number"] = line_number
            rows.append(row)

    return rows


def transcribe_clip(model, audio_path, batch_size):
    audio = whisperx.load_audio(str(audio_path))
    result = model.transcribe(audio, batch_size=batch_size)
    return "".join(segment.get("text", "").strip() for segment in result.get("segments", []))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", default="aligned_segments/train.jsonl")
    parser.add_argument("--base-dir", default="aligned_segments")
    parser.add_argument("--model", default="base")
    parser.add_argument("--language", default="zh")
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    parser.add_argument("--compute-type", default=None, choices=["float16", "float32", "int8"])
    parser.add_argument("--threshold", type=float, default=0.75)
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--report", default="aligned_segments/validation_report.jsonl")
    parser.add_argument("--bad-list", default="aligned_segments/bad_segments.txt")
    parser.add_argument("--clean-manifest", default="aligned_segments/train_clean.jsonl")

    args = parser.parse_args()
    args.compute_type = args.compute_type or ("float16" if args.device == "cuda" else "int8")

    manifest_path = Path(args.manifest)
    base_dir = Path(args.base_dir)
    report_path = Path(args.report)
    bad_list_path = Path(args.bad_list)
    clean_manifest_path = Path(args.clean_manifest)

    rows = load_manifest(manifest_path)
    if args.limit is not None:
        rows = rows[:args.limit]

    print(f"Loaded manifest rows: {len(rows)}")
    print(f"Loading WhisperX model: {args.model}")
    print(f"Device: {args.device}; compute type: {args.compute_type}; batch size: {args.batch_size}")

    model = whisperx.load_model(
        args.model,
        args.device,
        compute_type=args.compute_type,
        language=args.language,
        task="transcribe",
    )

    report_path.parent.mkdir(parents=True, exist_ok=True)
    bad_list_path.parent.mkdir(parents=True, exist_ok=True)
    clean_manifest_path.parent.mkdir(parents=True, exist_ok=True)

    ok_count = 0
    review_count = 0
    missing_count = 0

    with (
        report_path.open("w", encoding="utf-8") as report_file,
        bad_list_path.open("w", encoding="utf-8") as bad_file,
        clean_manifest_path.open("w", encoding="utf-8") as clean_file,
    ):
        for index, row in enumerate(rows, 1):
            audio_path = base_dir / row["audio"]
            expected_text = row.get("text", "")

            if not audio_path.exists():
                score = 0.0
                actual_text = ""
                status = "MISSING"
                missing_count += 1
            else:
                actual_text = transcribe_clip(model, audio_path, args.batch_size)
                score = similarity(expected_text, actual_text)
                status = "OK" if score >= args.threshold else "REVIEW"

                if status == "OK":
                    ok_count += 1
                else:
                    review_count += 1

            report_row = {
                "index": index,
                "line_number": row.get("_line_number"),
                "audio": row.get("audio"),
                "status": status,
                "score": round(score, 4),
                "duration": row.get("duration"),
                "start": row.get("start"),
                "end": row.get("end"),
                "expected_text": expected_text,
                "asr_text": actual_text,
            }

            report_file.write(json.dumps(report_row, ensure_ascii=False) + "\n")

            if status != "OK":
                bad_file.write(f"{index}\t{status}\t{score:.4f}\t{row.get('audio')}\n")
            else:
                clean_row = dict(row)
                clean_row.pop("_line_number", None)
                clean_file.write(json.dumps(clean_row, ensure_ascii=False) + "\n")

            print(f"{index}/{len(rows)} {status} score={score:.3f} {row.get('audio')}")

    print("Done.")
    print(f"OK: {ok_count}")
    print(f"Review: {review_count}")
    print(f"Missing: {missing_count}")
    print(f"Report saved to: {report_path}")
    print(f"Bad list saved to: {bad_list_path}")
    print(f"Clean manifest saved to: {clean_manifest_path}")


if __name__ == "__main__":
    main()
